### ISSUE TITLE
Doesn't build on my machine - Xubuntu 18.04

### ISSUE THREAD

**Issue by mslinklater** [JetSetIlly/Gopher2600#1]
1) Installed go V1.13.4 as detailed on Go website
2) Grabbed the repo
3) typed 'make release' as detailed in the README...

Output:

`link@link-FLO:~/Applications/Gopher2600$ make release
go build -gcflags '-c 3 -B -+ -wb=false' .
gopher2600.go:24:2: cannot find package "gopher2600/cartridgeloader" in any of:
	/usr/local/go/src/gopher2600/cartridgeloader (from $GOROOT)
	/home/link/go/src/gopher2600/cartridgeloader (from $GOPATH)
gopher2600.go:25:2: cannot find package "gopher2600/debugger" in any of:
	/usr/local/go/src/gopher2600/debugger (from $GOROOT)
	/home/link/go/src/gopher2600/debugger (from $GOPATH)
gopher2600.go:26:2: cannot find package "gopher2600/debugger/terminal" in any of:
	/usr/local/go/src/gopher2600/debugger/terminal (from $GOROOT)
	/home/link/go/src/gopher2600/debugger/terminal (from $GOPATH)
gopher2600.go:27:2: cannot find package "gopher2600/debugger/terminal/colorterm" in any of:
	/usr/local/go/src/gopher2600/debugger/terminal/colorterm (from $GOROOT)
	/home/link/go/src/gopher2600/debugger/terminal/colorterm (from $GOPATH)
gopher2600.go:28:2: cannot find package "gopher2600/debugger/terminal/plainterm" in any of:
	/usr/local/go/src/gopher2600/debugger/terminal/plainterm (from $GOROOT)
	/home/link/go/src/gopher2600/debugger/terminal/plainterm (from $GOPATH)
gopher2600.go:29:2: cannot find package "gopher2600/disassembly" in any of:
	/usr/local/go/src/gopher2600/disassembly (from $GOROOT)
	/home/link/go/src/gopher2600/disassembly (from $GOPATH)
gopher2600.go:30:2: cannot find package "gopher2600/errors" in any of:
	/usr/local/go/src/gopher2600/errors (from $GOROOT)
	/home/link/go/src/gopher2600/errors (from $GOPATH)
gopher2600.go:31:2: cannot find package "gopher2600/gui" in any of:
	/usr/local/go/src/gopher2600/gui (from $GOROOT)
	/home/link/go/src/gopher2600/gui (from $GOPATH)
gopher2600.go:32:2: cannot find package "gopher2600/gui/sdldebug" in any of:
	/usr/local/go/src/gopher2600/gui/sdldebug (from $GOROOT)
	/home/link/go/src/gopher2600/gui/sdldebug (from $GOPATH)
gopher2600.go:33:2: cannot find package "gopher2600/gui/sdlplay" in any of:
	/usr/local/go/src/gopher2600/gui/sdlplay (from $GOROOT)
	/home/link/go/src/gopher2600/gui/sdlplay (from $GOPATH)
gopher2600.go:34:2: cannot find package "gopher2600/modalflag" in any of:
	/usr/local/go/src/gopher2600/modalflag (from $GOROOT)
	/home/link/go/src/gopher2600/modalflag (from $GOPATH)
gopher2600.go:35:2: cannot find package "gopher2600/paths" in any of:
	/usr/local/go/src/gopher2600/paths (from $GOROOT)
	/home/link/go/src/gopher2600/paths (from $GOPATH)
gopher2600.go:36:2: cannot find package "gopher2600/performance" in any of:
	/usr/local/go/src/gopher2600/performance (from $GOROOT)
	/home/link/go/src/gopher2600/performance (from $GOPATH)
gopher2600.go:37:2: cannot find package "gopher2600/playmode" in any of:
	/usr/local/go/src/gopher2600/playmode (from $GOROOT)
	/home/link/go/src/gopher2600/playmode (from $GOPATH)
gopher2600.go:38:2: cannot find package "gopher2600/recorder" in any of:
	/usr/local/go/src/gopher2600/recorder (from $GOROOT)
	/home/link/go/src/gopher2600/recorder (from $GOPATH)
gopher2600.go:39:2: cannot find package "gopher2600/regression" in any of:
	/usr/local/go/src/gopher2600/regression (from $GOROOT)
	/home/link/go/src/gopher2600/regression (from $GOPATH)
gopher2600.go:40:2: cannot find package "gopher2600/television" in any of:
	/usr/local/go/src/gopher2600/television (from $GOROOT)
	/home/link/go/src/gopher2600/television (from $GOPATH)
gopher2600.go:41:2: cannot find package "gopher2600/wavwriter" in any of:
	/usr/local/go/src/gopher2600/wavwriter (from $GOROOT)
	/home/link/go/src/gopher2600/wavwriter (from $GOPATH)
Makefile:16: recipe for target 'release' failed
make: *** [release] Error 1
link@link-FLO:~/Applications/Gopher2600$ 
`

**Comment by mslinklater** [comment]
So this is $GOROOT and $GOPATH stuff... What should I set them to ?

**Comment by mslinklater** [comment]
I've created ~/go/src and put your repo in there. Still issues. It's looking for gopher2600 when the repo is named Gopher2600... changed that and got a load more errors...

`link@link-FLO:~/go/src/gopher2600$ make release
go build -gcflags '-c 3 -B -+ -wb=false' .
wavwriter/wav.go:28:2: cannot find package "github.com/go-audio/audio" in any of:
	/usr/local/go/src/github.com/go-audio/audio (from $GOROOT)
	/home/link/go/src/github.com/go-audio/audio (from $GOPATH)
wavwriter/wav.go:29:2: cannot find package "github.com/go-audio/wav" in any of:
	/usr/local/go/src/github.com/go-audio/wav (from $GOROOT)
	/home/link/go/src/github.com/go-audio/wav (from $GOPATH)
debugger/terminal/colorterm/easyterm/easyterm.go:33:2: cannot find package "github.com/pkg/term/termios" in any of:
	/usr/local/go/src/github.com/pkg/term/termios (from $GOROOT)
	/home/link/go/src/github.com/pkg/term/termios (from $GOPATH)
gui/sdldebug/guiloop.go:26:2: cannot find package "github.com/veandco/go-sdl2/sdl" in any of:
	/usr/local/go/src/github.com/veandco/go-sdl2/sdl (from $GOROOT)
	/home/link/go/src/github.com/veandco/go-sdl2/sdl (from $GOPATH)
Makefile:16: recipe for target 'release' failed
make: *** [release] Error 1
link@link-FLO:~/go/src/gopher2600$ 
`

Sorry, only done a tiny bit of Go a few years ago... I'm missing some setup.

**Comment by JetSetIlly** [comment]
It's because I hadn't included the go.mod file in the repository. I've fixed that now.

**Comment by mslinklater** [comment]
Success ! Currently running Combat.
