### ISSUE TITLE
TIA "undriven" pins

### ISSUE THREAD

**Issue by ale-79** [JetSetIlly/Gopher2600#16]
Following today discussion on AA about the undriven TIA pins, I did check on Gopher2600 and found a couple of issues.

Here is a test rom that I wrote a while ago (to show similar problems that were in Stella).
[tiadriven_test.zip](https://github.com/JetSetIlly/Gopher2600/files/7739864/tiadriven_test.zip)

The rom reads from addresses $00 to $0f, and displays the results on screen.

The registers are read with the instruction

`	lda $ff,x	`

with x ranging from $01 to $10.

In this case, the last value on the bus that will affect bits 0 - 5 is the value stored in ram address "$ff" (because the 6502 performs an extra fetch from the base address before adding the index, as described [here](https://archive.org/details/mcs-6500-family-hardware-manual-1976-01/page/n169/mode/2up?q=6500+mos+technology)).
The test rom changes that value at address $ff every 30 frames alternating between $ff and $00.

So with "random pins" off, bits 5 to 0 should alternate between "0" and "1" every half second. 
This is also the result that you (typically) get on real hardware.

On Gopher instead those bits currently take their value from the register address.

The second issue is with the input registers INPT0 to INPT5, where bit 6 must always read as "0", no matter how the "random pins" option is set.

**Comment by JetSetIlly** [comment]
Thanks for this bug report. 
 
> So with "random pins" off, bits 5 to 0 should alternate between "0" and "1" every half second. This is also the result that you (typically) get on real hardware.
> 
> On Gopher instead those bits currently take their value from the register address.

Okay. I've fixed that.

There were two problems here.

For some reason I hadn't included the "phantom read" for Zero Page Indexing addressing - although the cycles were accumulated correctly. Also, the value I was using to populate the undriven bits was wrong. It happened to work in other cases but for Zero Page Indexing, it was the wrong value.

> 
> The second issue is with the input registers INPT0 to INPT5, where bit 6 must always read as "0", no matter how the "random pins" option is set.

Right. I remember seeing something about that. I changed it for the CXBLPF register but I mustn't have seen a justification for changing the INPT registers. I'll take your bug report as the justification that I need.

https://user-images.githubusercontent.com/58750902/146655829-836cb0fc-4768-4e13-850d-4119b0c0bcdf.mp4

I'll commit the fix tomorrow after I've had a chance to review the changes.

**Comment by JetSetIlly** [comment]
I was thinking about how I could illustrate the "un-driven" pins issue in the emulator.

What I've come up with is a new debugging window that shows the 6507 pins and the current state of the address and data bus.

So, in the video below, I'm stepping forward by a single video cycle (color clock). We can see the pins and the current value on the bus changing with each cycle.

At cycle 3 of the LDA $ff,x instruction we can see the value of RAM address $ff being put on the bus.

And then in cycle 4, when the indexing has been applied, we can see how the driven pins take the value from the TIA register but how the un-driven pins are not updated.

https://user-images.githubusercontent.com/58750902/146789756-851decbe-75f8-4ea4-b628-3d0fbbdad6cb.mp4

There's a lot going on here but it might be useful to help understand unexpected side-effects in a program.

**Comment by ale-79** [comment]
> it might be useful to help understand unexpected side-effects in a program.

I agree. I updated and played a bit with it and it's really interesting to see in action.
