### ISSUE TITLE
Seg fault trying to debug a ROM

### ISSUE THREAD

**Issue by mslinklater** [JetSetIlly/Gopher2600#2]
Console:

`link@link-FLO:~/go/src/gopher2600$ ./gopher2600 debug ~/Code/retrotools/combat.bin 
* symbols error: no symbols file for /home/link/Code/retrotools/combat.bin
* error running debugger initialisation script: script error: cannot open script file (open /home/link/.config/gopher2600/debuggerInit: no such file or directory)
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x66fa97]

goroutine 1 [running, locked to thread]:
gopher2600/debugger/script.(*Rescribe).TermRead(0x0, 0xc00000ab00, 0xff, 0xff, 0xc00001a380, 0x12, 0x6, 0xc000062720, 0xc0000e1220, 0x203000, ...)
	/home/link/go/src/gopher2600/debugger/script/rescribe.go:90 +0x37
gopher2600/debugger.(*Debugger).inputLoop(0xc000001c80, 0x85e4a0, 0x0, 0x0, 0xc000495ad0, 0x1)
	/home/link/go/src/gopher2600/debugger/inputloop.go:170 +0xc83
gopher2600/debugger.(*Debugger).Start(0xc000001c80, 0xc0000184e0, 0x2a, 0x7ffd13125425, 0x25, 0x7d722c, 0x4, 0x0, 0x0, 0x0, ...)
	/home/link/go/src/gopher2600/debugger/debugger.go:223 +0x668
main.debug.func1(0x865760, 0xc0000835f0)
	/home/link/go/src/gopher2600/gopher2600.go:206 +0xf5
main.debug(0xc0000e2180, 0x0, 0x0)
	/home/link/go/src/gopher2600/gopher2600.go:223 +0x7f3
main.main()
	/home/link/go/src/gopher2600/gopher2600.go:76 +0x304
`

**Comment by JetSetIlly** [comment]
Fixed. That was one of those schoolboy errors caused by never having run the debugger without an init script.

**Comment by JetSetIlly** [comment]
More on this:

The TestDebugger() function was calling dbg.Start() with no script file name. The debugger was correctly testing for that condition but not the condition where a script name is provided but the file doesn't exist. I've improved the test scripts so that both conditions are considered

**Comment by mslinklater** [comment]
Confirm fix. Not crashing any more.
