### ISSUE TITLE
Portable Version?

### ISSUE THREAD

**Issue by XYZ964** [JetSetIlly/Gopher2600#24]
Hi, first of all thanks for your emulator.
My request is quite obvious, could you provide a portable version?
Like many people, I dont like the installation versions.
Thanks in advance, hope you will consider it.
Best regards!

**Comment by JetSetIlly** [comment]
Hello,

Do you mean a version that will run in a web browser?  I've done some investigation into that and conducted some experiments, but the performance just isn't very good yet. It's definitely a long-term goal however.

Regards

**Comment by XYZ964** [comment]
Hi!
No, no at all.  I meant somethig far more simple.
All of the files used by the emulator compressed in a zip file.
So users simply decompress the archive and all the files needed by the emulator are at hand.
Like most of the emultors, without the need to execute an installer..
Regards

**Comment by JetSetIlly** [comment]
Well, the binaries I provide in each release are just executables, they're not installers. But I suppose if the machine you're running on doesn't have the correct support libraries they won't work.

I'll look into the possibility of creating and distributing a flatpak for Linux systems. I'll look at the other platforms after that.

Thanks for the suggestion!

**Comment by XYZ964** [comment]
You are 100% right.
I tested the emulator on a second PC and, to my surprise, i found it was an executable, not an installer. 
The other PC didnt have the libraries, so I do apologize for my mistake.
Best wishes with the project and thanks for your time, really appreciate it.
