### ISSUE TITLE
ROM selection doesn't work on Windows (v0.31 and v0.32)?

### ISSUE THREAD

**Issue by Al-Nafuur** [JetSetIlly/Gopher2600#30]
![grafik](https://github.com/JetSetIlly/Gopher2600/assets/15229085/890e4147-189b-4149-b496-73edae81d709)

**Comment by JetSetIlly** [comment]
Thanks for the bug report. I think I know what the problem is. I'll have to look more closely this evening.

In the meantime, can you put a ROM file or a folder or zip file of ROM files in the same location as the gopher2600 executable and try again. I think that should work.

**Comment by Al-Nafuur** [comment]
> In the meantime, can you put a ROM file or a folder or zip file of ROM files in the same location as the gopher2600 executable and try again. I think that should work.

That worked

**Comment by JetSetIlly** [comment]
v0.32.1 should have fixed this issue. https://github.com/JetSetIlly/Gopher2600/releases/tag/v0.32.1

**Comment by Al-Nafuur** [comment]
v0.32.1 fixed the issue
