### ISSUE TITLE
include domain name in module paths; local module paths may be reserved in the future

### ISSUE THREAD

**Issue by mewmew** [JetSetIlly/Gopher2600#4]
First of, really cool work @JetSetIlly! I tried running Gopher2600 on two games and it worked well :)

![screenshot_2020-03-21_23:10:38](https://user-images.githubusercontent.com/1414531/77237520-434deb80-6bc9-11ea-95cf-e9bf4bfea1be.png)

As I wanted to dive into the documentation of the project, I checked the GoDoc page. At the end of the page, I noticed these warnings:

```
The go get command cannot install this package because of the following issues:

    Unrecognized import path "gopher2600/wavwriter" (gopher2600.go:42:2)
    Unrecognized import path "gopher2600/gui/sdldebug" (gopher2600.go:32:2)
    Unrecognized import path "gopher2600/gui/sdlimgui" (gopher2600.go:33:2)
    Unrecognized import path "gopher2600/disassembly" (gopher2600.go:29:2)
    Unrecognized import path "gopher2600/playmode" (gopher2600.go:38:2)
```

If possible, I'd suggest updating the module path to `github.com/jetsetilly/gopher2600`, as this includes the domain name in the fully qualified import path. One reason this is important is that there is a proposal to reserve specific path prefixes for local (user-defined) modules (e.g. `local/gopher2600`); see golang/go#37641. Since the Gopher2600 project is hosted on a remote site, it makes sense to include the full domain name in the module path.

Wish you all the best and happy coding.

Cheers,
Robin

**Comment by JetSetIlly** [comment]
Hi Robin,

Thanks for trying it out! I'm pretty new to Go and haven't really got my head around the new module system. I'll make the changes you've mentioned later this weekend.

If you're interested in documentation I have another repository that I'll be using for more in depth documentation. https://github.com/JetSetIlly/Gopher2600-Dev-Docs

Not much in there at the moment but I'll be adding to it next week. Somebody has expressed an interest in using the emulator in an machine learning project so I need to document the controller system and all that kind of stuff.

Thanks again.

**Comment by mewmew** [comment]
> Thanks for trying it out! I'm pretty new to Go and haven't really got my head around the new module system. I'll make the changes you've mentioned later this weekend.

No worries :) We're all here to learn and improve.

The change I mentioned would look something like #5.

**Comment by mewmew** [comment]
> Not much in there at the moment but I'll be adding to it next week. Somebody has expressed an interest in using the emulator in a machine learning project so I need to document the controller system and all that kind of stuff.

Yeah, I saw that too. Would be really cool! Coincidentally, I've also been looking at reinforcement learning these last few days, and was thus excited to see [gold](https://github.com/aunum/gold) repo of @aunum as referenced from the Reddit thread.

> If you're interested in documentation I have another repository that I'll be using for more in depth documentation. https://github.com/JetSetIlly/Gopher2600-Dev-Docs

Thanks for putting the docs online! It's great to have both API level documentation and high-level documentation.

Cheers,
Robin
